### ISSUE TITLE
Static IP and machine batch

### ISSUE THREAD

**Issue by devilldog** [CenturyLinkCloud/chef-provisioning-vsphere#31]
Hi, I am new to chef provisioning-vsphere, I have been able to make simple recipes build, the problem I am having is I need to use static ip's ( i know ... so last century ) but when I want to build 4 servers with 4 different IP's how do I update the machine options once in the machine batch ? to change the IP based on the machine ? Thanks for any help !
Robert

**Comment by mwrock** [comment]
I am guessing you may be using `with_machine_options`. This can be convenient but is not ideal when you have different machines that need different settings. Like the IP in your case.

Instead of using `with_machine_options`, assign the machine options to a hash variable. Change the ip address for each machine and pass it to the `machine_options` attribute. So instead of:

```
with_machine_options :bootstrap_options => {
  num_cpus: 2,
  memory_mb: 4096,
  network_name: ["vlan_20_172.21.20"],
  datacenter: 'datacenter_name',
  resource_pool: 'cluster',
  template_name: 'path to template',
  datastore: "my_data_store",
  customization_spec: {
    ipsettings: {
      ip: '192.168.3.4',
      subnetMask: '255.255.255.0',
      gateway: ["192.168.3.1"],
      dnsServerList: ['1.2.3.31','1.2.3.41']
    },
    :domain => 'local'
  }
  :ssh => {
    :user => 'root',
    :password => 'password',
    :paranoid => false,
  }
}
```

you would have:

```
machine_options = {
  :bootstrap_options => {
    num_cpus: 2,
    memory_mb: 4096,
    network_name: ["vlan_20_172.21.20"],
    datacenter: 'datacenter_name',
    resource_pool: 'cluster',
    template_name: 'path to template',
    datastore: "my_data_store",
    customization_spec: {
      ipsettings: {
        ip: '192.168.3.4',
        subnetMask: '255.255.255.0',
        gateway: ["192.168.3.1"],
        dnsServerList: ['1.2.3.31','1.2.3.41']
      },
      :domain => 'local'
    }
    :ssh => {
      :user => 'root',
      :password => 'password',
      :paranoid => false,
    }
  }
}
```

Then inside your batch, your machine resources would take this variable:

```
machine_options[:bootstrap_options][:customization_spec][:ipsettings][:ip] = '1.2.3.4'
machine "my_machine_name" do
  machine_options machine_options
  run_list ['my_cookbook::default']
end
```

does that make sense?

**Comment by devilldog** [comment]
indeed  Thanks Matt!
