### ISSUE TITLE
Support for vcloud

### ISSUE THREAD

**Issue by asciifaceman** [CenturyLinkCloud/chef-provisioning-vsphere#35]
I was just wondering if there is any intention to support vcloud or if this would technically already work. I know there is knife-vcair but it is just "different" in how it handles provisioning. 

If anybody more knowledgeable could chime in I would really appreciate it.

**Comment by adamleff** [comment]
@asciifaceman you may be able to use https://github.com/chef/chef-provisioning-fog for this.  Fog has vCloud Director / vCloud Air support, though you may have to specify alternate API endpoint paths if using vCloud Air On-Demand because VMware changed the API path between the "subscription" and the "on demand" offerings.  :sob:

**Comment by asciifaceman** [comment]
Yes, It has been a nightmare trying to find a way to support IAC on vmware. I can't believe I actually prefer vsphere over their cloud offerings.
vCloud hasn't been overly helpful, and I could literally drive to an AWS loft easier than getting help.

**Comment by asciifaceman** [comment]
Closed since we have a productive conversation in /chef-partners/knife-vcair/issues/33#issuecomment-145030731

**Comment by adamleff** [comment]
@asciifaceman I echo your pain, and we're trying to help make it better at Chef.  Thanks for your contributions raising issues, etc.

**Comment by asciifaceman** [comment]
No problem, I am a very active chef guy (or try to be). after a stint of deploying 60+ boxes at a time with chef in AWS, the struggle is real on vCloud.
