### ISSUE TITLE
Linked Clone issue with Windows 

### ISSUE THREAD

**Issue by bradwilliamson** [CenturyLinkCloud/chef-provisioning-vsphere#9]
Hello, I am provisioning afrom a Windows 2012 R2 server template, and have set use_linked_clone: false;. It appears that the newly provisoned machine remains a linked clone of the template I'm using even with the value set to false.  Below is the section where I have the use_linked_clone setting.  

 with_machine_options :bootstrap_options => {
  use_linked_clone: false,
  num_cpus: 2,
  memory_mb: 4096,

**Comment by mwrock** [comment]
Could you provision with debug logging? This will spit out the entire `VirtualMachineCloneSpec` sent to vmware. Then return the `VirtualMachineRelocateSpec`portion. If will look like this:
```
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-8499"),
    diskMoveType: :moveChildMostDiskBacking,
    host: HostSystem("host-5865")
  ),
```
If it is truly creating a linked clone, it will include `diskMoveType: :moveChildMostDiskBacking`. Otherwise it is a full clone.

Just curious, what about the VM makes you think it is a linked clone? (not saying its not but this is not very discoverable).

Also, make sure you are using the latest release (currently 0.6.0). We have had issues in the past where linked clones were unintentionally created but those have been resolved.

**Comment by bradwilliamson** [comment]
I believe this has been resolved updating to the latest version. It was being reported in vCenter Server it was a linked clone.

**Comment by mwrock** [comment]
good to hear updating this fixed it.
